language: python

python:
  - "2.7"

install:
  - "pip install --upgrade setuptools --use-mirrors"

before_script:
  - npm install

script:
  - python setup.py test
  - grunt travis --verbose # add --force to overlook JS test failures
